version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ${ZOOKEEPER_CONTAINER}
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: ${KAFKA_CONTAINER}
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock